channels:
  - conda-forge
  - nodefaults
dependencies:
  - sqlite
  - requests
  - pandas
  - jinja2
  - xarray
  - netcdf4
  - dask
  - matplotlib
  - cartopy
  - zarr
  - s3fs
  - seaborn
  - ipykernel
  - 'libnetcdf<4.9'
  - r-base
  - r-ggplot2
  - r-loader
  - r-transformer
  - r-visualizer
  - r-irkernel
  - r-geoprocessor
